version: "3.8"

services:
    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: travel_agency
            MYSQL_USER: traveluser
            MYSQL_PASSWORD: travelpassword
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./db/init:/docker-entrypoint-initdb.d

volumes:
    db_data:
